<?php

namespace TBStatBundle\Repository\MySQL;

/**
 * TBTelemetryStatAvgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TBTelemetryStatAvgRepository extends \Doctrine\ORM\EntityRepository
{
}
