<?php

namespace TBStatBundle\Repository\MySQL;

/**
 * TBTelemetryStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TBTelemetryStatRepository extends \Doctrine\ORM\EntityRepository
{
}
